@startuml

hide fields
hide Host methods
hide saint.SoloHarmonizer methods
hide saint.SoloHarmonizerEditor methods
hide saint.IntervalGetterFactory methods

class Host

namespace saint {
class SoloHarmonizer
class SoloHarmonizerEditor

abstract class EditorsFactoryView {
  setUseHostPlayhead(bool)
  getUseHostPlayhead(): bool
  setMidiFile(path)
  getMidiFile(): optional<path>
  getMidiFileTrackNames(): vector<string>
  setPlayedTrack(int)
  getPlayedTrack(): optional<int>
  setHarmonyTrack(int)
  getHarmonyTrack(): optional<int>
}

abstract class ProcessorsFactoryView {
  getState(): const vector<uint8_t>&
  setState(vector<uint8_t>)
  hasIntervalGetter()
  getIntervalGetter(): shared_ptr<IntervalGetter>
  useHostPlayhead(): bool
}

class IntervalGetterFactory
class IntervalGetter {
  getHarmoInterval(double timeInCrotchets, optional<float> pitch): optional<float>
}

SoloHarmonizerEditor -o SoloHarmonizer
SoloHarmonizer *-- ProcessorsFactoryView
SoloHarmonizer *-- EditorsFactoryView
SoloHarmonizerEditor o-- EditorsFactoryView

EditorsFactoryView --|> IntervalGetterFactory
ProcessorsFactoryView --|> IntervalGetterFactory
SoloHarmonizer o. IntervalGetter
IntervalGetter --* IntervalGetterFactory

}

Host *-- saint.SoloHarmonizerEditor

@enduml
