@startuml

hide fields
hide SoloHarmonizer methods
hide SoloHarmonizerEditor methods
hide IntervalGetterFactory methods
hide juce_AudioPlayhead methods
hide Playhead methods
hide SoloHarmonizerVst methods
hide ProcessCallbackDrivenPlayhead methods
hide HostDrivenPlayhead methods
hide IntervalGetter methods

abstract class Playhead
class SoloHarmonizer
class SoloHarmonizerEditor
class SoloHarmonizerVst
class ProcessCallbackDrivenPlayhead
class HostDrivenPlayhead

abstract class EditorsFactoryView {
  setMidiFile(path)
  getMidiFile(): optional<path>
  getMidiFileTrackNames(): vector<string>
  setPlayedTrack(int)
  getPlayedTrack(): optional<int>
  setHarmonyTrack(int)
  getHarmonyTrack(): optional<int>
}

abstract class ProcessorsFactoryView {
  getState(): const vector<uint8_t>&
  setState(vector<uint8_t>)
  hasIntervalGetter()
  getIntervalGetter(): shared_ptr<IntervalGetter>
}

class IntervalGetterFactory
class IntervalGetter

SoloHarmonizerVst *- IntervalGetterFactory
SoloHarmonizerVst *-- SoloHarmonizer
SoloHarmonizerVst *.. ProcessCallbackDrivenPlayhead
SoloHarmonizerVst *.. HostDrivenPlayhead
SoloHarmonizerEditor -o SoloHarmonizer
SoloHarmonizer o-- ProcessorsFactoryView
SoloHarmonizerEditor o-- EditorsFactoryView

EditorsFactoryView <|-- IntervalGetterFactory
ProcessorsFactoryView <|-- IntervalGetterFactory
SoloHarmonizer o. IntervalGetter
IntervalGetter --* IntervalGetterFactory

juce_AudioPlayhead -o SoloHarmonizerVst
SoloHarmonizerVst -|> Playhead
Playhead <|-- ProcessCallbackDrivenPlayhead
Playhead <|-- HostDrivenPlayhead
Playhead --o SoloHarmonizer

@enduml
